### ISSUE TITLE
Schema serialization rewrite and migration

### ISSUE THREAD

**Issue by randomPoison** [jamiebrynes7/spatialos-sdk-rs#121]
After a couple of fruitful-but-failed attempts at rewriting the schema serialization logic (#89, #101), I've now got a better idea of how to improve the serialization system. At this point, the problem is figuring out how to migrate to the improved system without having to do a single, massive PR. The goal of this ticket is to lay out a plan for that migration, and to act as a tracker for the progress.

The previous pass at rewriting the serialization system is archived in a [fork of the repository](https://github.com/randomPoison/spatialos-sdk-rs/tree/serialization-rewrite).

[Progress is also tracked in a project](https://github.com/jamiebrynes7/spatialos-sdk-rs/projects/5).

## Rationale

There are a number of problems that I am attempting to solve with this rewrite:

* **Safety issues with schema data objects**. The way that the schema data objects are exposed is wildly unsafe. It does not enforce the required ownership for data, exposing soundness holes in safe Rust code.
* **Better encode schema serialization rules** using Rust's type system. The current setup doesn't do a good job statically enforcing that schema types match the semantics of the schema language.
* **Provide a more idiomatic API**. If possible, we should more closely mirror how [serde](https://serde.rs/) handles serialization.

## Migration Steps

The goal is to break this work up into smaller steps that can each be merged in one at a time in the hopes of making the migration work more manageable.

* [x] Restructure module hierarchy. This is an easy first step and will help make future refactorings less messy. (#122)
  * [x] Move `schema` out of `internal`.
  * [x] Move schema primitive types into submodule of `schema`.
  * [x] Move schema object types into separate submodules of `schema`.
* [x] Remove `SchemaFieldContainer`. The current setup is incompatible with the safety fixes, so getting this done will help keep the later changes smaller. (#124)
* [x] Address schema object safety issues. This is relatively self-contained work, and can be done without changing how serialization itself is handled.
  * [x] `SchemaObject` (#127)
  * [x] `SchemaComponentData` (#128)
  * [x] `SchemaComponentUpdate` (#129)
  * [x] `SchemaCommandRequest` (#129)
  * [x] `SchemaCommandResponse` (#129)
* [x] Rework schema serialization setup.
  * [x] Compare the current setup to the ideal setup.
  * [x] Determine more granular migration steps.
  * [x] Get collection types (list, map, and option) and object types represented properly in the serialization traits. This will basically mean updating SchemaFieldPrimitive to be a more generalized SchemaField trait. It will also allow us to drastically simplify code generation, which will made the subsequent steps easier.
  * [x] Split off the IndexedField and ArrayField traits.
  * [x] Update Component to more directly defer to the main serialization traits.
  * [x] Split out separate Update, CommandResponse, and CommandRequest traits.

**Comment by randomPoison** [comment]
Here's a summary of the current state of the schema object serialization setup and a comparison with the alternate version designed for #89.

## Current System

Schema data serialization currently works as follows:

* The `SchemaFieldContainer` type wraps a reference to the `SchemaObject` and the field ID, and adds a generic type parameter to track the intended type of the field.
  * Exposes the various operations that can be performed on the field (e.g. getting the value, indexing into an array field, adding a value to the field, etc.).
  * The various serialization traits are implemented on different monomorphizations of `SchemaFieldContainer` (e.g. `SchemaFieldContainer<SchemaInt>`) rather than being implemented directly on the different schema types.
* The `SchemaPrimitiveField` trait exposes the various operations defined for the primitive schema types.
  * These correspond to the various `Schema_Get*`, `Schema_Index*`, `Schema_Get*Count`, `Schema_Add*`, `Schema_Add*List` functions in the C API.
  * Has a type parameter corresponding to the Rust type generated from that schema type. This would be better as an associated types, since there's generally only one valid Rust type that would correspond to each schema type.
  * Implementations are done via the `impl_primitive_field!` macro, since the implementation is almost identical for all types.
  * The `SchemaBytesField`, `SchemaStringField`, and `SchemaObjectField` traits are similar to `SchemaPrimitiveField`, but for byte arrays, strings, and sub-objects respectively. These seem unnecessary, and should ideally be rolled back into `SchemaPrimitiveField`.
* `TypeConversion` trait is what actually gets implemented for schema object types.
* `Component` is implemented for each component type.
  * Defines functions for serializing a component and all of its associated types (updates and commands). This makes it a bit of a mega-trait that does a lot of things. 
  * The `Component` implementation will generally just defer to the `TypeConversion` for any given type, making the `Component` trait itself somewhat boilerplate-y.

## Overhauled System

This is the version of serialization that I arrived at for #101, after a bunch of experimentation and iteration. You can see the source code [here](https://github.com/randomPoison/spatialos-sdk-rs/blob/e702ff2ffa738f7ce5b0a8b5162b376fd956900f/spatialos-sdk/src/worker/schema.rs). A lot of this is also explained in the write-up in #89.

* `SchemaField` trait defines the operations that are valid on all schema types.
  * `get_field`, `add_field`, `has_update`, `get_update`, `add_update`.
  * Has an associated type `RustType` which specifies which Rust type corresponds to that schema type.
  * Does not support indexing into the fields because collection types (`option<T>`, `list<T>`, `map<K, V>`) can't be indexed, i.e. you can't have an `option<list<T>>` or a `list<map<K, V>>`.
* `IndexedField` extends `SchemaField`
  * Adds `field_count` and `index_field`.
  * Does not support the more efficient array API because object fields do support array access (i.e. there is no `Schema_GetObjectList` or `Schema_AddObjectList`).
* `ArrayField` extends `IndexedField`, providing a more efficient way to get and set a list field for types that support it.
  * Only implemented for the built-in primitive types.
* All three of these traits (`SchemaField`, `IndexedField`, and `ArrayField`) are sealed and cannot be implemented directly on user types.
* `SchemaObjectType` is the trait that is implemented for non-primitive schema types.
  * Directly converts a `SchemaObject` into the corresponding Rust type (or vice versa).
  * Any type implementing `SchemaObjectType` gets a blanket impl of `SchemaField` and `IndexedField`.
* The `Component` trait extends `SchemaObjectType`, with all serialization delegated to `SchemaObjectType` automatically. This [removes all of the boilerplate](https://github.com/randomPoison/spatialos-sdk-rs/blob/e702ff2ffa738f7ce5b0a8b5162b376fd956900f/spatialos-sdk/tests/manual_serialization.rs#L75) currently needed for `Component`. Same goes for component updates and commands.

## Unresolved Questions

* Do we need error handling for serialization? The current system has all serialization functions return a `Result`, allowing serialization to be fallible. This isn't strictly necessary, since the C underlying serialization functions in the C API can never fail, but it may still be desirable if we want to support a user-defined data validation step post-serialization.
* Is there a way to break up the conversion into smaller steps that can be merged in separately? As it stands, doing this work all at once would still be a smaller effort than what was previously attempted in #101, but it would still be a pretty big change to review and merge all at once.

**Comment by randomPoison** [comment]
# Schema Data Object Safety

The current way the schema data objects (`SchemaObject`, `SchemaCommandRequest`, `SchemaCommandResponse`, `SchemaComponentUpdate`, and `SchemaComponentData`) are setup is very unsafe. Specifically, there are two major issues:

* The objects don't have associated lifetimes, but the data itself is sometimes not owned by the data object. Specifically, in the case were the data is coming in as part of an `OpList`, the `OpList` owns the data and the data is freed when the `OpList` is dropped. This means it's pretty easy to have a `SchemaComponentData` outlive the data it's pointing to, and end up with a dangling pointer.
* The objects don't free the underlying data when dropped, so in the case where the data *is* owned (e.g. when sending updates to the runtime), the data is never freed. This isn't technically a safety issue, but it does lead to a lot of leaked memory pretty quickly.

## Overhauled System

Just do exactly what's described in #101 🤷‍♀

## Migration Steps

I believe we should be able to do this for one type at a time without too much issue.

**Comment by jamiebrynes7** [comment]
This seems like a very sensible plan and I like the direction this is going. :heart: Feel free to create a Project to track each part if you'd like. :smile: 

---

> Do we need error handling for serialization? The current system has all serialization functions return a Result, allowing serialization to be fallible. This isn't strictly necessary, since the C underlying serialization functions in the C API can never fail, but it may still be desirable if we want to support a user-defined data validation step post-serialization.

I think we can probably drop the `Result` from the serialization functions. Like you say the serialization can't fail, or at least, this isn't exposed to the user at all. Looking at the [current generated code](https://github.com/jamiebrynes7/spatialos-sdk-rs/blob/master/project-example/src/generated.rs), we never actually return an `Err` from anything in the serialization code. :grimacing:

A post-serialization validation step could be interesting, what do you envision that looking like? 

---

> Is there a way to break up the conversion into smaller steps that can be merged in separately? As it stands, doing this work all at once would still be a smaller effort than what was previously attempted in #101, but it would still be a pretty big change to review and merge all at once.

My guess is that might be tricky, I think logical ordered commits that can easily be reviewed in (relative) isolation in a larger PR might be the way to go here. 

I could see a scenario where we do it in two PRs. 

1. `SchemaField`, `ArrayField`, `IndexedField`, and `SchemaObjectType` trait changes.
2. `TypeConversion` and `Component` trait changes.

But you are much more familiar with the code in question, so you'll be able to make that call better than I could. :smile:

**Comment by randomPoison** [comment]
Got a project setup for tracking this now 😁: https://github.com/jamiebrynes7/spatialos-sdk-rs/projects/5

---

Okay, after doing the work for #124 I think I have an idea of how to break up the changes to serialization:

1. Get collection types (`list`, `map`, and `option`) and object types represented properly in the serialization traits. This will basically mean updating `SchemaFieldPrimitive` to be a more generalized `SchemaField` trait. It will also allow us to *drastically* simplify code generation, which will made the subsequent steps easier.
1. Split off the `IndexedField` and `ArrayField` traits.
1. Update `Component` to more directly defer to the main serialization traits.
1. Split out separate `Update`, `CommandResponse`, and `CommandRequest` traits.

That first step may also be able to be broken into multiple PRs, depending on how easy it is to update just one collection type at a time.

**Comment by jamiebrynes7** [comment]
I believe the last of this work was completed in #166!
