### ISSUE TITLE
Look into templating for Rust

### ISSUE THREAD

**Issue by jamiebrynes7** [jamiebrynes7/spatialos-sdk-rs#16]
Would be nice to not have to reinvent the wheel

**Comment by davedissian** [comment]
What do you mean by templating here?

**Comment by jamiebrynes7** [comment]
As in templating for code generation. Something that ideally is native in the Rust ecosystem. Think T4 for C#

**Comment by davedissian** [comment]
Looks like the biggest library is https://github.com/Keats/tera

**Comment by jamiebrynes7** [comment]
Ended up using https://github.com/ReSpeak/t4rust
