### ISSUE TITLE
Automatic component registration

### ISSUE THREAD

**Issue by randomPoison** [jamiebrynes7/spatialos-sdk-rs#57]
Currently users have to manually build the `ComponentDatabase` in order to enable automatic serialization. This means that they have to remember to add every single component in the standard schema library, their project, and any types from third-party libraries they use. This process is tedious and error-prone, and would benefit from an automated solution. There are two possible approaches I can think of:

First, have the code generation process generate a helper function that builds a `ComponentDatabase` with all the component types. Since code generation currently knows about all component types in the project, it should be relatively trivial to do this. However, #56 proposes that we change that, so we'll have to be cognizant of how these two proposals interact.

The other approach is to use the [inventory](https://crates.io/crates/inventory) crate to gather up all component types defined in all compiled crates (including third-party crates) and build a `ComponentDatabase` from them. This may interact better with #56 if we can't build the component database directly as part of code generation.

**Comment by jamiebrynes7** [comment]
I think this is actually quite important - I'm starting to work on fleshing out the snapshot APIs (#13) - which requires the snapshot to know about the component vtables and component ids. 

Sadly this then makes it incompatible with the `Entity` struct which knows about generic `Component` types. 

These can be unified behind the `ComponentDatabase` but this increases boilerplate for users as they have to pass a reference to the database everywhere - if we can statically instantiate a `ComponentDatabase` for all generated components, this problem goes away.

Possibly [`lazy_static`](https://github.com/rust-lang-nursery/lazy-static.rs) may be of use here as well?

**Comment by randomPoison** [comment]
How is automatic registration incompatible with the `Entity` builder? It seems to me like the two are orthogonal: One is for registering the vtables when creating the connection object, the other is for gathering the raw (i.e. not-yet-serialized) component data when creating/updating a component. Am I missing something?

**Comment by jamiebrynes7** [comment]
Ah sorry - its not automatic registration which is incompatible with `Entity`, its that the `Entity` struct is incompatible with `SnapshotInputStream` (or anywhere you have serialized data and a component database).

This means that refactoring the `Entity` struct to use the component database under the hood makes automatic registration _more_ important.

---

In particular - you can't reconstruct the `drop_fn` field required currently by `Entity`: https://github.com/jamiebrynes7/spatialos-sdk-rs/blob/master/spatialos-sdk/src/worker/entity.rs#L12 without explicit knowledge of which `Component` impl the serialized data is for. 

This is fine when writing out serialized data as its expected that the user has initiated that and we can acquire type information from them.

This becomes a problem when you need to read an entity's data from serialized form (`SnapshotInputStream` or `EntityQueryResponseOp` for example) as you need to deserialize the data without knowledge of a specific component implementation (this is where vtables comes into play).

**Comment by randomPoison** [comment]
I think I'm going to try to tackle this one soon, I'm already running into issues resulting from me forgetting to register component types: https://forums.improbable.io/t/debugging-encountered-unknown-component-id/5395
