### ISSUE TITLE
Download the SpatialOS SDK as part of cargo-spatial

### ISSUE THREAD

**Issue by randomPoison** [jamiebrynes7/spatialos-sdk-rs#74]
Users need to have the SDK downloaded before they can compile the Rust SDK, and this is currently handled as a manual step before they can even build their project. We should handle this automatically as part of `cargo-spatial`. This should include specifying a library version in your `Spatial.toml` configuration file.

**Comment by jamiebrynes7** [comment]
Going to grab this to become more familiar with the `cargo-spatial` part of the codebase :smile:
