### ISSUE TITLE
Download the spatial CLI as part of cargo-spatial

### ISSUE THREAD

**Issue by randomPoison** [jamiebrynes7/spatialos-sdk-rs#75]
We currently require that the user install the `spatial` CLI tool separately in order to be able to use `cargo-spatial`. We should reasonably be able to automate this in `cargo-spatial`, automatically downloading the CLI and installing it to a local directory if the user doesn't have it installed already.

**Comment by jamiebrynes7** [comment]
There's an installer which I believe has a CLI interface, so we can grab that and install using the installer (which will have reasonable defaults).
