### ISSUE TITLE
Implement cleared fields on updates

### ISSUE THREAD

**Issue by jamiebrynes7** [jamiebrynes7/spatialos-sdk-rs#84]
Noticed that there is a TODO about cleared fields https://github.com/jamiebrynes7/spatialos-sdk-rs/blob/master/spatialos-sdk/src/worker/internal/schema.rs#L73

We need to implement this to enable clearing of lists, maps, and options in component updates.

**Comment by jamiebrynes7** [comment]
@randomPoison I think you've done this as part of #121 right?

**Comment by randomPoison** [comment]
Ah, yup, this was handled in #132!
